### ISSUE TITLE
Package missing on fresh install (compress?)

### ISSUE THREAD

**Issue by kribba** [mattiasrunge/MURRiX#112]
ribba@surtsey:/usr/share/MURRiX$ ./murrix.bin.js server
Tue Nov 04 2014 22:22:03 GMT+0100 (CET)  session    INFO   Trying to load existing sessions from /usr/share/MURRiX/sessions/
Tue Nov 04 2014 22:22:03 GMT+0100 (CET)  session    INFO   Loaded 0 session(s) from disk!
Tue Nov 04 2014 22:22:03 GMT+0100 (CET)  session    INFO   Setting session disk write timer to 10 seconds...
Tue Nov 04 2014 22:22:04 GMT+0100 (CET)  server     INFO   Starting HTTP server...

/usr/share/MURRiX/node_modules/mongodb/lib/server.js:181
          process.nextTick(function() { throw err; })
                                              ^
Error: Most middleware (like compress) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/usr/share/MURRiX/node_modules/express/lib/express.js:89:13)
    at self.start (/usr/share/MURRiX/lib/server.js:42:21)
    at /usr/share/MURRiX/murrix.js:41:17
    at /usr/share/MURRiX/lib/db.js:17:7
    at /usr/share/MURRiX/node_modules/mongodb/lib/db.js:175:16
    at null.<anonymous> (/usr/share/MURRiX/node_modules/mongodb/lib/server.js:179:11)
    at g (events.js:180:16)
    at emit (events.js:98:17)
    at errorHandler (/usr/share/MURRiX/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:339:24)
    at g (events.js:180:16)

**Comment by mattiasrunge** [comment]
Will not be an issue in v3
